# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextDifferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField(max_length=1000000000)),
                ('changed', models.TextField(max_length=1000000000)),
            ],
        ),
    ]
