# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-22 07:11
from __future__ import unicode_literals

from django.db import migrations, models
import fuel_price.models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel_price', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OilPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oil_type', models.CharField(max_length=10)),
                ('data', fuel_price.models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
